import assert from 'node:assert/strict';
import { installTouchControls } from '../src/touch-controls.js';
import { stepSteering } from '../src/flight.js';
const elements=new Map(),windowEvents=new Map(),classes=new Set();
function element(id){if(!elements.has(id))elements.set(id,{style:{},events:new Map(),setPointerCapture(){},getBoundingClientRect(){return {left:0,top:0,width:120,height:120};},addEventListener(name,fn){this.events.set(name,fn);}});return elements.get(id);}
globalThis.document={getElementById:element,body:{classList:{add:name=>classes.add(name)}}};
globalThis.window={matchMedia:()=>({matches:true}),addEventListener:(name,fn)=>windowEvents.set(name,fn)};
globalThis.innerWidth=850;globalThis.innerHeight=400;
const control={steerX:0,steerY:0,x:400,y:180};let shots=0,lasers=0,active=true,turns=[];
const touch=installTouchControls({control,playing:()=>active,turn:code=>turns.push(code),fire:()=>shots++,lock:()=>{control.locking=true;},release:()=>{lasers++;control.locking=false;},cancel:()=>{control.shooting=control.locking=false;},unlock(){}});
const event=(id,name,pointerId,x,y,pointerType='touch')=>element(id).events.get(name)({pointerId,clientX:x,clientY:y,pointerType,preventDefault(){},stopPropagation(){}});
assert.ok(classes.has('touch-mode'),'coarse pointer enables touch UI');
event('touch-stick','pointerdown',1,100,30);stepSteering(control,new Set(),.1);assert.ok(control.steerX>0&&control.steerY>0);
event('touch-aim','pointerdown',2,600,200);assert.equal(shots,1);assert.equal(control.shooting,true);
event('touch-aim','pointermove',2,620,180);assert.equal(control.x,430);assert.equal(control.y,150);assert.ok(control.touchX>0,'aim finger does not change movement finger');
event('touch-lock','pointerdown',3,780,330);assert.equal(control.shooting,false);assert.equal(control.locking,true);
event('touch-lock','pointermove',3,760,310);assert.equal(control.x,400);
event('touch-lock','pointerup',3,760,310);assert.equal(lasers,1);assert.equal(control.shooting,true,'aim finger resumes normal fire');
event('touch-aim','pointerup',2,620,180);assert.equal(control.shooting,false);assert.ok(control.touchX>0);
event('touch-stick','pointerup',1,100,30);assert.equal(control.touchX,undefined);
event('touch-lock','pointerdown',4,780,330);event('touch-lock','pointercancel',4,780,330);assert.equal(control.locking,false);assert.equal(lasers,1,'cancellation does not fire locks');
event('touch-aim','pointerdown',5,600,200);active=false;touch.reset();event('touch-aim','pointermove',5,700,100);assert.equal(control.shooting,false);
active=true;event('touch-left','click');event('touch-front','click');event('touch-right','click');assert.deepEqual(turns,['KeyQ','KeyR','KeyE']);
event('touch-aim','pointerdown',6,600,200,'mouse');assert.equal(control.shooting,false);
// A second finger can turn without click synthesis or cancelling the stick.
event('touch-stick','pointerdown',10,100,30);const heldX=control.touchX;
event('touch-left','pointerdown',11,300,330);event('touch-front','pointerdown',12,350,330);event('touch-right','pointerdown',13,400,330);
assert.deepEqual(turns.slice(-3),['KeyQ','KeyR','KeyE']);assert.equal(control.touchX,heldX);
const turnCount=turns.length;event('touch-right','click',13,400,330);assert.equal(turns.length,turnCount,'synthetic click does not turn twice');
event('touch-aim','pointerdown',14,600,200);event('touch-aim','lostpointercapture',14,600,200);
assert.equal(control.touchX,heldX,'losing aim capture does not cancel movement');
event('touch-lock','pointerdown',15,780,330);event('touch-lock','pointercancel',15,780,330);
assert.equal(control.touchX,heldX,'cancelling a lock does not cancel movement');
globalThis.innerHeight=350;windowEvents.get('resize')();assert.equal(control.touchX,heldX,'browser toolbar resize preserves active touch');
event('touch-stick','pointermove',10,30,80);assert.ok(control.touchX<0,'stick keeps responding after other fingers cancel');
event('touch-stick','pointerdown',16,90,30);event('touch-stick','pointerup',10,30,80);assert.ok(control.touchX>0,'new stick touch replaces a stale pointer');
windowEvents.get('pointerup')({pointerId:16});assert.equal(control.touchX,undefined,'window release handles missed element release');
event('touch-stick','pointerdown',17,100,30);globalThis.innerWidth=400;windowEvents.get('resize')();assert.equal(control.touchX,undefined,'rotation cancels old gesture');
console.log('PASS: automatic touch UI, simultaneous movement/aim, lock drag/release, pointer cancellation, pause reset, view buttons and mouse isolation.');
